# http package

# Style classes
classes: {
  domain: {
    style.fill: "#e8f4fc"
    style.font-color: "#000"
  }
  service: {
    style.fill: "#f0e8fc"
    style.font-color: "#000"
  }
  factory: {
    style.fill: "#e8fce8"
    style.font-color: "#000"
  }
  value: {
    style.fill: "#f8f8f8"
    style.font-color: "#000"
  }
}

# Legend
legend: {
  label: "Color Legend (DDD)"
  style.stroke: "#999"
  style.fill: "#fafafa"
  near: top-right

  aggregate: {
    label: "Domain Model"
    shape: class
    class: domain
  }
  service: {
    label: "Service"
    shape: class
    class: service
  }
  factory: {
    label: "Factory"
    shape: class
    class: factory
  }
  options: {
    label: "Value Object"
    shape: class
    class: value
  }
}

# Files
server: {
  label: "server.go"
  class: factory

  Server: {
    shape: class
    stereotype: "<<struct>>"

    "+SetActivityObserver(fn func())": ""
    "+Serve(ctx context.Context, addr string, ready func(boundAddr string))": "error"
  }

  NewMultiServer: {
    shape: class
    stereotype: "<<factory>>"

    "multi": "*internal/serve.MultiState"
    "return": "(*internal/adapter/http.Server, error)"
  }

  NewServer: {
    shape: class
    stereotype: "<<factory>>"

    "state": "*internal/serve.State"
    "return": "(*internal/adapter/http.Server, error)"
  }


}

# Dependencies
server.NewMultiServer -> server.Server: "returns"
server.NewServer -> server.Server: "returns"
