import type { UIGraph } from '../types';
import { fixture } from './fixture';

const SCHEMA_PREFIX = 'archai.uigraph/';

/**
 * Load the UIGraph data with a fallback chain:
 * 1. /archgraph.json (generated by archai export ui)
 * 2. /archgraph.sample.json (committed sample)
 * 3. fixture (hardcoded rich sample)
 */
export async function loadGraph(): Promise<UIGraph> {
  // Try generated archgraph.json first
  let graph = await tryFetch('/archgraph.json');
  if (graph) return graph;

  // Fall back to committed sample
  graph = await tryFetch('/archgraph.sample.json');
  if (graph) return graph;

  // Fall back to fixture
  console.info('[loadGraph] Using built-in fixture as fallback');
  return fixture;
}

async function tryFetch(url: string): Promise<UIGraph | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;

    const data = await res.json();
    if (!validateSchema(data)) {
      console.warn(`[loadGraph] Invalid schema in ${url}:`, data.schema);
      return null;
    }
    console.info(`[loadGraph] Loaded from ${url}`);
    return data as UIGraph;
  } catch (err) {
    console.debug(`[loadGraph] Failed to fetch ${url}:`, err);
    return null;
  }
}

function validateSchema(data: unknown): data is UIGraph {
  if (typeof data !== 'object' || data === null) return false;
  const schema = (data as Record<string, unknown>).schema;
  return typeof schema === 'string' && schema.startsWith(SCHEMA_PREFIX);
}
