# golang package

# Legend
legend: {
  label: "Color Legend (DDD)"
  style.stroke: "#999"
  style.fill: "#fafafa"
  near: top-right

  aggregate: {
    label: "Domain Model"
    shape: class
    style.fill: "#e8f4fc"
    style.font-color: "#000"
  }
  service: {
    label: "Service"
    shape: class
    style.fill: "#f0e8fc"
    style.font-color: "#000"
  }
  factory: {
    label: "Factory"
    shape: class
    style.fill: "#e8fce8"
    style.font-color: "#000"
  }
  options: {
    label: "Value Object"
    shape: class
    style.fill: "#f8f8f8"
    style.font-color: "#000"
  }
}

# Files
reader: {
  label: "reader.go"
  style.fill: "#e8fce8"

  NewReader: {
    shape: class
    stereotype: "<<factory>>"

    "return": "internal/service.ModelReader"
  }


}

# Dependencies
